/**
 * Store conformance, SP-DP-002: read Icechunk repositories over real HTTP
 * against fixtures generated by the Python icechunk reference implementation
 * (see tools/spectral-prism-py/scripts/generate_icechunk_fixtures.py):
 * branch/tag/snapshot pinning, all three chunk payload types (inline, native,
 * virtual), snapshot id surfaced for provenance, and the authorization hook
 * on repository reads and virtual chunk fetches alike.
 */
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import * as zarr from 'zarrita';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { startFixtureServer, type FixtureServer } from '../testing/http-fixture-server';
import { createIcechunkStore, type IcechunkRef } from './icechunk';
import type { RequestAuthorizer } from './types';

const FIXTURES = join(__dirname, '..', '..', 'fixtures', 'stores');
const VIRTUAL_HOST = 'spectral-prism-fixture.invalid';

interface NativeExpected {
  dtype: string;
  shape: number[];
  refs: Record<string, { snapshotId: string; values: number[] }>;
  wide: { shape: number[]; values: number[] };
}

interface VirtualExpected {
  dtype: string;
  shape: number[];
  snapshotId: string;
  values: number[];
}

const nativeExpected: NativeExpected = JSON.parse(
  readFileSync(join(FIXTURES, 'expected', 'icechunk-native.json'), 'utf8'),
);
const virtualExpected: VirtualExpected = JSON.parse(
  readFileSync(join(FIXTURES, 'expected', 'icechunk-virtual.json'), 'utf8'),
);

let server: FixtureServer;

beforeAll(async () => {
  server = await startFixtureServer(FIXTURES);
});

afterAll(async () => {
  await server.close();
});

/** Rewrites the committed placeholder host to the live fixture server. */
function rewriteVirtualHost(): RequestAuthorizer {
  return (req) => {
    if (req.url.hostname === VIRTUAL_HOST) {
      const live = new URL(server.url);
      req.url.protocol = live.protocol;
      req.url.host = live.host;
    }
    return req;
  };
}

async function readArray(ref: IcechunkRef, path: string) {
  const store = await createIcechunkStore(`${server.url}/icechunk-native`, { ref });
  const group = await zarr.open(store.readable, { kind: 'group' });
  const arr = await zarr.open(group.resolve(path), { kind: 'array' });
  return { store, region: await zarr.get(arr) };
}

describe('Icechunk native repo over HTTP', () => {
  it('reads branch main (default ref) and records the resolved snapshot id', async () => {
    const expected = nativeExpected.refs['branch:main'];
    const { store, region } = await readArray({ branch: 'main' }, 'cube');
    expect(region.data).toBeInstanceOf(Int16Array);
    expect([...region.data]).toEqual(expected?.values);
    expect(store.snapshotId).toBe(expected?.snapshotId);
    expect(store.ref).toEqual({ branch: 'main' });
  });

  it('reads tag v1.0: earlier bytes, earlier snapshot id', async () => {
    const expected = nativeExpected.refs['tag:v1.0'];
    const { store, region } = await readArray({ tag: 'v1.0' }, 'cube');
    expect([...region.data]).toEqual(expected?.values);
    expect(store.snapshotId).toBe(expected?.snapshotId);
    expect(store.snapshotId).not.toBe(nativeExpected.refs['branch:main']?.snapshotId);
  });

  it('reads a pinned snapshot id directly', async () => {
    const snapshotId = nativeExpected.refs['tag:v1.0']?.snapshotId as string;
    const expected = nativeExpected.refs[`snapshot:${snapshotId}`];
    const { store, region } = await readArray({ snapshot: snapshotId }, 'cube');
    expect([...region.data]).toEqual(expected?.values);
    expect(store.snapshotId).toBe(snapshotId);
  });

  it('reads native (non-inline) chunk payloads', async () => {
    const { region } = await readArray({ branch: 'main' }, 'wide');
    expect(region.shape).toEqual(nativeExpected.wide.shape);
    expect([...region.data]).toEqual(nativeExpected.wide.values);
  });

  it('applies the authorization hook to repository object reads', async () => {
    const from = server.requests.length;
    const store = await createIcechunkStore(`${server.url}/icechunk-native`, {
      authorize: (req) => {
        req.headers.set('authorization', 'Bearer icechunk-token');
        return req;
      },
    });
    const group = await zarr.open(store.readable, { kind: 'group' });
    const arr = await zarr.open(group.resolve('cube'), { kind: 'array' });
    await zarr.get(arr);
    const requests = server.requests.slice(from);
    expect(requests.length).toBeGreaterThan(0);
    expect(requests.every((r) => r.authorization === 'Bearer icechunk-token')).toBe(true);
  });
});

describe('Icechunk over a range-ignoring server (defensive slicing)', () => {
  it('still reads correct values when the server ignores Range and returns 200', async () => {
    // AuthorizedHttpStorage requests byte ranges for repository objects; a host
    // that ignores Range and returns the whole 200 body must not corrupt the
    // read (the store slices the body to the requested range).
    const badServer = await startFixtureServer(FIXTURES, { ignoreRange: true });
    try {
      const store = await createIcechunkStore(`${badServer.url}/icechunk-native`, {
        // authorize forces the AuthorizedHttpStorage path rather than upstream
        // HttpStorage, so the fix under test is exercised.
        authorize: (req) => req,
      });
      const group = await zarr.open(store.readable, { kind: 'group' });
      const cube = await zarr.open(group.resolve('cube'), { kind: 'array' });
      const region = await zarr.get(cube);
      expect([...region.data]).toEqual(nativeExpected.refs['branch:main']?.values);

      const wide = await zarr.open(group.resolve('wide'), { kind: 'array' });
      expect([...(await zarr.get(wide)).data]).toEqual(nativeExpected.wide.values);
    } finally {
      await badServer.close();
    }
  });
});

describe('Icechunk virtual chunks over HTTP', () => {
  it('resolves virtual references through the URL-rewriting hook, with ranged reads', async () => {
    const from = server.requests.length;
    const store = await createIcechunkStore(`${server.url}/icechunk-virtual`, {
      authorize: rewriteVirtualHost(),
    });
    const group = await zarr.open(store.readable, { kind: 'group' });
    const arr = await zarr.open(group.resolve('vcube'), { kind: 'array' });
    const region = await zarr.get(arr);

    expect(region.data).toBeInstanceOf(Int16Array);
    expect(region.shape).toEqual(virtualExpected.shape);
    expect([...region.data]).toEqual(virtualExpected.values);
    expect(store.snapshotId).toBe(virtualExpected.snapshotId);

    // The committed refs carry offset+length into the blob, so every blob read
    // must be a ranged GET that lands on the rewritten (live) host.
    const blobRequests = server.requests.slice(from).filter((r) => r.path.startsWith('/blobs/'));
    expect(blobRequests.length).toBeGreaterThan(0);
    expect(blobRequests.every((r) => r.method === 'GET' && r.range !== null)).toBe(true);
  });

  it('fails closed when virtual hosts are not resolvable (no rewrite configured)', async () => {
    const store = await createIcechunkStore(`${server.url}/icechunk-virtual`);
    const group = await zarr.open(store.readable, { kind: 'group' });
    const arr = await zarr.open(group.resolve('vcube'), { kind: 'array' });
    await expect(zarr.get(arr)).rejects.toThrow();
  });
});
